// DO NOT EDIT: this file was generated by gen/gen_fixtures.go,
// changes made will be overwritten upon regeneration.
//
// To regenerate all fixtures, use make go_fixturegen; to regenerate only this
// test's fixtures run go generate ./pkg/relayer/miner/miner_test.go.
package miner_test

var (
	// marshaledMinableRelaysHex are the hex encoded strings of serialized
	// relayer.MinedRelays which have been pre-mined to difficulty 16 by
	// populating the signature with random bytes. It is intended for use
	// in tests.
	marshaledMinableRelaysHex = []string{
		"0a140a121210ed3df6a4c7e1cef222d7103a25ceebdb",
		"0a140a121210ec4d7dfd783aed31e7b8bedd28639b94",
		"0a140a121210e47441726693a02fb643d872b3884ae4",
		"0a140a121210e77d8fdd8d65f8c8326ffc4eb56d1201",
		"0a140a1212106015840f643a73a12263e2fadc8e0a14",
	}

	// marshaledUnminableRelaysHex are the hex encoded strings of serialized
	// relayer.MinedRelays which have been pre-mined to **exclude** relays with
	// difficulty 16 (or greater). Like marshaledMinableRelaysHex, this is done
	// by populating the signature with random bytes. It is intended for use in
	// tests.
	marshaledUnminableRelaysHex = []string{
		"0a140a1212105c5871f88cf2d01392f2d3ee86260e32",
		"0a140a12121062e3c2598825e08a047a203f19e98991",
		"0a140a121210360bf57dab9ba6a236dc4b561f3280e3",
		"0a140a121210933c8012b14ba39e2c19a9fa0d95371b",
		"0a140a121210ecbbeaf7bf4243741d106f01cae3886b",
	}
)
